# Generated by Django 5.0.7 on 2024-07-17 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("0c7fd9f1-b6d1-4936-93e1-10b572f214da"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
