# Generated by Django 5.0.7 on 2024-07-17 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="age",
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="actor",
            name="id",
            field=models.CharField(
                default=uuid.UUID("cd7a5ab3-c82f-478f-8bc9-f6f43f84345c"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
